apiVersion: batch/v1
kind: CronJob
metadata:
  name: csearch.scraper
  namespace: postgres-operator
spec:
  schedule: "5 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          volumes:
            - name: congress-storage
              persistentVolumeClaim:
                claimName: congress-pvc
          initContainers:
            - name: config-data
              image: ubuntu:hirsute
              command: ["/bin/sh","-c"]
              args: ["apt update; apt install -y wget tar zstd git; git clone https://github.com/unitedstates/congress.git /congress/temp; mv /congress/temp/* /congress/; cd /congress; wget https://www.dropbox.com/s/8gge1nghs81vw3i/data.tar.zst?dl=1; tar --zstd -xvf data.tar.zst?dl=1;"]
              volumeMounts:
                - mountPath: /congress
                  name: congress-storage
          containers:
            - name: "congress-api-sha256-1"
              image: 'registry.digitalocean.com/csearch/scraper'

              imagePullPolicy: Always
              env:
                - name: DB_VENDOR
                  value: "postgres"
                - name: DB_ADDR
                  valueFrom: { secretKeyRef: { name: csearch-db-pguser-csearch-db, key: host } }
                - name: DB_URI
                  valueFrom: { secretKeyRef: { name: csearch-db-pguser-csearch-db, key: uri } }
                - name: DB_PORT
                  valueFrom: { secretKeyRef: { name: csearch-db-pguser-csearch-db, key: port } }
                - name: DB_DATABASE
                  valueFrom: { secretKeyRef: { name: csearch-db-pguser-csearch-db, key: dbname } }
                - name: DB_USER
                  valueFrom: { secretKeyRef: { name: csearch-db-pguser-csearch-db, key: user } }
                - name: DB_PASSWORD
                  valueFrom: { secretKeyRef: { name: csearch-db-pguser-csearch-db, key: password } }
              volumeMounts:
                - name: congress-storage
                  mountPath: /congress
              resources:
                requests:
                  cpu: 100m
                  memory: 64Mi
                limits:
                  cpu: 500m
                  memory: 1024Mi
          restartPolicy: OnFailure


