apiVersion: apps/v1
kind: Deployment
metadata:
  name: csearch.scraper
  namespace: postgres-operator
spec:
  selector:
    matchLabels:
      app: csearch.scraper
  replicas: 1
  template:
    metadata:
      labels:
        app: csearch.scraper
    spec:
      volumes:
        - name: congress-storage
          persistentVolumeClaim:
            claimName: congress-pvc
      initContainers:
        - name: git-cloner
          image: alpine/git
          args:
            - clone
            - --single-branch
            - --
            - https://github.com/unitedstates/congress.git
            - /congress
          volumeMounts:
            - mountPath: /congress
              name: congress-storage
        - name: config-data
          image: ubuntu:hirsute
          command: ["/bin/sh","-c"]
          args: ["apt update; apt install -y wget tar zstd; wget https://www.dropbox.com/s/z3kqzw593jsx19m/data.tar.zst?dl=1; tar xvf data.tar.zstd?dl=1 -C /congress;"]
          volumeMounts:
            - mountPath: /congress
              name: congress-storage
      containers:
        - name: "congress-api-sha256-1"
          image: 'gcr.io/csearch-335113/github.com/s4njee/congress_scraper@sha256:b094e540988d28f3c91fde469ff4cfa79e84b840545c86ac9fa793a1a6e054f0'

          imagePullPolicy: Always
          env:
            - name: DB_VENDOR
              value: "postgres"
            - name: DB_ADDR
              valueFrom: { secretKeyRef: { name: csearch-db-pguser-csearch-db, key: host } }
            - name: DB_URI
              valueFrom: { secretKeyRef: { name: csearch-db-pguser-csearch-db, key: uri } }
            - name: DB_PORT
              valueFrom: { secretKeyRef: { name: csearch-db-pguser-csearch-db, key: port } }
            - name: DB_DATABASE
              valueFrom: { secretKeyRef: { name: csearch-db-pguser-csearch-db, key: dbname } }
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: csearch-db-pguser-csearch-db, key: user } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: csearch-db-pguser-csearch-db, key: password } }
          volumeMounts:
            - name: congress-storage
              mountPath: /congress
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi

